name: Build and Publish Flatpak Repo

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-flatpak:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Flatpak repo
        run: |
          flatpak-builder --force-clean --repo=repo build-dir io.github.fernandomema.MinecraftServerManager.yml

      - name: Export Flatpak repo for GitHub Pages
        run: |
          mkdir -p public
          flatpak build-export public repo stable

      - name: Create .nojekyll
        run: touch public/.nojekyll

      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
