name: Build and Test

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-gi python3-yaml gir1.2-gtk-3.0

    - name: Test AppImage build
      run: |
        chmod +x build-appimage.sh
        ./build-appimage.sh

    - name: Verify AppImage
      run: |
        ls -la minecraft-server-manager-gtk-x86_64.AppImage
        file minecraft-server-manager-gtk-x86_64.AppImage

    - name: Upload AppImage for testing
      uses: actions/upload-artifact@v4
      with:
        name: test-appimage-pr-${{ github.event.number }}
        path: minecraft-server-manager-gtk-x86_64.AppImage
        retention-days: 7

    - name: Comment on PR with download link
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          // Get the file size
          const filePath = './minecraft-server-manager-gtk-x86_64.AppImage';
          const stats = fs.statSync(filePath);
          const fileSizeInBytes = stats.size;
          const fileSizeInMB = (fileSizeInBytes / (1024*1024)).toFixed(2);
          
          const comment = `## 🎮 AppImage Build Ready for Testing!
          
          Your changes have been successfully built into an AppImage for testing.
          
          **📦 Download:** [minecraft-server-manager-gtk-x86_64.AppImage](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          
          **📊 Build Info:**
          - Size: ${fileSizeInMB} MB
          - Build ID: ${{ github.run_id }}
          - Commit: ${{ github.event.pull_request.head.sha }}
          
          **🚀 How to test:**
          1. Download the AppImage from the artifacts section of the workflow run
          2. Make it executable: \`chmod +x minecraft-server-manager-gtk-x86_64.AppImage\`
          3. Run it: \`./minecraft-server-manager-gtk-x86_64.AppImage\`
          
          **⚠️ Note:** This AppImage will be available for 7 days for testing purposes.`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
